export const categories = [
        {
           "id":18,
           "name":"bakery",
           "slug":"bakery",
           "parent":0,
           "description":"food items",
           "display":"products",
           "image":{
              "id":70,
              "date_created":"2020-06-09T07:56:39",
              "date_created_gmt":"2020-06-09T07:56:39",
              "date_modified":"2020-06-09T07:56:39",
              "date_modified_gmt":"2020-06-09T07:56:39",
              "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/grocerystore.png",
              "name":"grocerystore",
              "alt":""
           },
           "menu_order":0,
           "count":5,
           "_links":{
              "self":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories\/18"
                 }
              ],
              "collection":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories"
                 }
              ]
           }
        },
        {
           "id":22,
           "name":"Fruits",
           "slug":"fruits",
           "parent":0,
           "description":"fruits",
           "display":"products",
           "image":{
              "id":57,
              "date_created":"2020-06-09T07:47:15",
              "date_created_gmt":"2020-06-09T07:47:15",
              "date_modified":"2020-06-09T07:47:15",
              "date_modified_gmt":"2020-06-09T07:47:15",
              "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Fruits.png",
              "name":"Fruits",
              "alt":""
           },
           "menu_order":0,
           "count":1,
           "_links":{
              "self":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories\/22"
                 }
              ],
              "collection":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories"
                 }
              ]
           }
        },
        {
           "id":20,
           "name":"Men's Clothing",
           "slug":"men-clothing",
           "parent":0,
           "description":"Men's variety",
           "display":"products",
           "image":{
              "id":35,
              "date_created":"2020-06-09T07:29:09",
              "date_created_gmt":"2020-06-09T07:29:09",
              "date_modified":"2020-06-09T07:29:09",
              "date_modified_gmt":"2020-06-09T07:29:09",
              "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Men-Clothing-Image.jpg",
              "name":"Men Clothing Image",
              "alt":""
           },
           "menu_order":0,
           "count":10,
           "_links":{
              "self":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories\/20"
                 }
              ],
              "collection":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories"
                 }
              ]
           }
        },
        {
           "id":19,
           "name":"Women's Clothing",
           "slug":"women-clothing",
           "parent":0,
           "description":"Women's all clothing",
           "display":"products",
           "image":{
              "id":36,
              "date_created":"2020-06-09T07:30:38",
              "date_created_gmt":"2020-06-09T07:30:38",
              "date_modified":"2020-06-09T07:30:38",
              "date_modified_gmt":"2020-06-09T07:30:38",
              "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Women-Clothing-Image.jpg",
              "name":"Women Clothing Image",
              "alt":""
           },
           "menu_order":0,
           "count":7,
           "_links":{
              "self":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories\/19"
                 }
              ],
              "collection":[
                 {
                    "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/categories"
                 }
              ]
           }
        }
];

export const products = [
    {
       "id":68,
       "name":"Corn Oil Bottle (500ml)",
       "slug":"corn-oil-bottle-500ml",
       "permalink":"https:\/\/pos.t-techsolutions.org\/product\/corn-oil-bottle-500ml\/",
       "date_created":"2020-06-09T07:55:20",
       "date_created_gmt":"2020-06-09T07:55:20",
       "date_modified":"2020-06-09T07:55:20",
       "date_modified_gmt":"2020-06-09T07:55:20",
       "type":"simple",
       "status":"publish",
       "featured":false,
       "catalog_visibility":"visible",
       "description":"<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n",
       "short_description":"",
       "sku":"2342355678",
       "price":"10.99",
       "regular_price":"11.99",
       "sale_price":"10.99",
       "date_on_sale_from":null,
       "date_on_sale_from_gmt":null,
       "date_on_sale_to":null,
       "date_on_sale_to_gmt":null,
       "price_html":"<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>11.99<\/bdi><\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>10.99<\/bdi><\/span><\/ins>",
       "on_sale":true,
       "purchasable":true,
       "total_sales":3,
       "virtual":false,
       "downloadable":false,
       "downloads":[
          
       ],
       "download_limit":-1,
       "download_expiry":-1,
       "external_url":"",
       "button_text":"",
       "tax_status":"taxable",
       "tax_class":"",
       "manage_stock":false,
       "stock_quantity":null,
       "stock_status":"instock",
       "backorders":"no",
       "backorders_allowed":false,
       "backordered":false,
       "sold_individually":false,
       "weight":"",
       "dimensions":{
          "length":"",
          "width":"",
          "height":""
       },
       "shipping_required":true,
       "shipping_taxable":true,
       "shipping_class":"",
       "shipping_class_id":0,
       "reviews_allowed":true,
       "average_rating":"0.00",
       "rating_count":0,
       "related_ids":[
          66,
          60,
          64,
          62
       ],
       "upsell_ids":[
          
       ],
       "cross_sell_ids":[
          
       ],
       "parent_id":0,
       "purchase_note":"",
       "categories":[
          {
             "id":18,
             "name":"bakery",
             "slug":"bakery"
          }
       ],
       "tags":[
          
       ],
       "images":[
          {
             "id":69,
             "date_created":"2020-06-09T07:55:15",
             "date_created_gmt":"2020-06-09T07:55:15",
             "date_modified":"2020-06-09T07:55:15",
             "date_modified_gmt":"2020-06-09T07:55:15",
             "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Corn-Oil-Bottle-500ml.jpg",
             "name":"Corn Oil Bottle (500ml)",
             "alt":""
          }
       ],
       "attributes":[
          
       ],
       "default_attributes":[
          
       ],
       "variations":[
          
       ],
       "grouped_products":[
          
       ],
       "menu_order":0,
       "meta_data":[
          {
             "id":781,
             "key":"_yith_pos_multistock_enabled",
             "value":"no"
          },
          {
             "id":782,
             "key":"_yith_pos_multistock",
             "value":[
                
             ]
          },
          {
             "id":802,
             "key":"_wc_facebook_sync_enabled",
             "value":"no"
          },
          {
             "id":807,
             "key":"_ywbc_barcode_protocol",
             "value":"EAN13"
          },
          {
             "id":808,
             "key":"_ywbc_barcode_value",
             "value":"68"
          },
          {
             "id":809,
             "key":"_ywbc_barcode_display_value",
             "value":"0000000000680"
          },
          {
             "id":810,
             "key":"ywbc_barcode_display_value_custom_field",
             "value":"0000000000680"
          },
          {
             "id":812,
             "key":"_ywbc_barcode_filename",
             "value":"\/customers\/f\/5\/6\/t-techsolutions.org\/httpd.www\/pos\/wp-content\/uploads\/yith-barcodes\/Image68_EAN13_68.png"
          }
       ],
       "yithPosImage":{
          "id":69,
          "date_created":"2020-06-09T07:55:15",
          "date_created_gmt":"2020-06-09T07:55:15",
          "date_modified":"2020-06-09T07:55:15",
          "date_modified_gmt":"2020-06-09T07:55:15",
          "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Corn-Oil-Bottle-500ml-300x237.jpg",
          "name":"Corn Oil Bottle (500ml)",
          "alt":""
       },
       "_links":{
          "self":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/68"
             }
          ],
          "collection":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products"
             }
          ]
       }
    },
    {
       "id":66,
       "name":"Italian Pasta (500g)",
       "slug":"italian-pasta-500g",
       "permalink":"https:\/\/pos.t-techsolutions.org\/product\/italian-pasta-500g\/",
       "date_created":"2020-06-09T07:54:20",
       "date_created_gmt":"2020-06-09T07:54:20",
       "date_modified":"2020-06-09T07:54:20",
       "date_modified_gmt":"2020-06-09T07:54:20",
       "type":"simple",
       "status":"publish",
       "featured":false,
       "catalog_visibility":"visible",
       "description":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.<\/p>\n",
       "short_description":"",
       "sku":"",
       "price":"2.00",
       "regular_price":"2.00",
       "sale_price":"",
       "date_on_sale_from":null,
       "date_on_sale_from_gmt":null,
       "date_on_sale_to":null,
       "date_on_sale_to_gmt":null,
       "price_html":"<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>2.00<\/bdi><\/span>",
       "on_sale":false,
       "purchasable":true,
       "total_sales":4,
       "virtual":false,
       "downloadable":false,
       "downloads":[
          
       ],
       "download_limit":-1,
       "download_expiry":-1,
       "external_url":"",
       "button_text":"",
       "tax_status":"taxable",
       "tax_class":"",
       "manage_stock":false,
       "stock_quantity":null,
       "stock_status":"instock",
       "backorders":"no",
       "backorders_allowed":false,
       "backordered":false,
       "sold_individually":false,
       "weight":"",
       "dimensions":{
          "length":"",
          "width":"",
          "height":""
       },
       "shipping_required":true,
       "shipping_taxable":true,
       "shipping_class":"",
       "shipping_class_id":0,
       "reviews_allowed":true,
       "average_rating":"0.00",
       "rating_count":0,
       "related_ids":[
          60,
          62,
          64,
          68
       ],
       "upsell_ids":[
          
       ],
       "cross_sell_ids":[
          
       ],
       "parent_id":0,
       "purchase_note":"",
       "categories":[
          {
             "id":18,
             "name":"bakery",
             "slug":"bakery"
          }
       ],
       "tags":[
          
       ],
       "images":[
          {
             "id":67,
             "date_created":"2020-06-09T07:54:16",
             "date_created_gmt":"2020-06-09T07:54:16",
             "date_modified":"2020-06-09T07:54:16",
             "date_modified_gmt":"2020-06-09T07:54:16",
             "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Italian-Pasta-500g.jpg",
             "name":"Italian Pasta (500g)",
             "alt":""
          }
       ],
       "attributes":[
          
       ],
       "default_attributes":[
          
       ],
       "variations":[
          
       ],
       "grouped_products":[
          
       ],
       "menu_order":0,
       "meta_data":[
          {
             "id":756,
             "key":"_yith_pos_multistock_enabled",
             "value":"no"
          },
          {
             "id":757,
             "key":"_yith_pos_multistock",
             "value":[
                
             ]
          },
          {
             "id":775,
             "key":"_wc_facebook_sync_enabled",
             "value":"no"
          },
          {
             "id":813,
             "key":"_ywbc_barcode_protocol",
             "value":"EAN13"
          },
          {
             "id":814,
             "key":"_ywbc_barcode_value",
             "value":"66"
          },
          {
             "id":815,
             "key":"_ywbc_barcode_display_value",
             "value":"0000000000666"
          },
          {
             "id":816,
             "key":"ywbc_barcode_display_value_custom_field",
             "value":"0000000000666"
          },
          {
             "id":818,
             "key":"_ywbc_barcode_filename",
             "value":"\/customers\/f\/5\/6\/t-techsolutions.org\/httpd.www\/pos\/wp-content\/uploads\/yith-barcodes\/Image66_EAN13_66.png"
          }
       ],
       "yithPosImage":{
          "id":67,
          "date_created":"2020-06-09T07:54:16",
          "date_created_gmt":"2020-06-09T07:54:16",
          "date_modified":"2020-06-09T07:54:16",
          "date_modified_gmt":"2020-06-09T07:54:16",
          "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Italian-Pasta-500g-300x237.jpg",
          "name":"Italian Pasta (500g)",
          "alt":""
       },
       "_links":{
          "self":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/66"
             }
          ],
          "collection":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products"
             }
          ]
       }
    },
    {
       "id":64,
       "name":"Rice Cakes with Chia Seeds",
       "slug":"rice-cakes-with-chia-seeds",
       "permalink":"https:\/\/pos.t-techsolutions.org\/product\/rice-cakes-with-chia-seeds\/",
       "date_created":"2020-06-09T07:53:37",
       "date_created_gmt":"2020-06-09T07:53:37",
       "date_modified":"2020-06-09T07:53:37",
       "date_modified_gmt":"2020-06-09T07:53:37",
       "type":"simple",
       "status":"publish",
       "featured":false,
       "catalog_visibility":"visible",
       "description":"<p>Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.<\/p>\n",
       "short_description":"",
       "sku":"564564345",
       "price":"5.99",
       "regular_price":"7.99",
       "sale_price":"5.99",
       "date_on_sale_from":null,
       "date_on_sale_from_gmt":null,
       "date_on_sale_to":null,
       "date_on_sale_to_gmt":null,
       "price_html":"<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>7.99<\/bdi><\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>5.99<\/bdi><\/span><\/ins>",
       "on_sale":true,
       "purchasable":true,
       "total_sales":2,
       "virtual":false,
       "downloadable":false,
       "downloads":[
          
       ],
       "download_limit":-1,
       "download_expiry":-1,
       "external_url":"",
       "button_text":"",
       "tax_status":"taxable",
       "tax_class":"",
       "manage_stock":false,
       "stock_quantity":null,
       "stock_status":"instock",
       "backorders":"no",
       "backorders_allowed":false,
       "backordered":false,
       "sold_individually":false,
       "weight":"",
       "dimensions":{
          "length":"",
          "width":"",
          "height":""
       },
       "shipping_required":true,
       "shipping_taxable":true,
       "shipping_class":"",
       "shipping_class_id":0,
       "reviews_allowed":true,
       "average_rating":"0.00",
       "rating_count":0,
       "related_ids":[
          66,
          60,
          68,
          62
       ],
       "upsell_ids":[
          
       ],
       "cross_sell_ids":[
          
       ],
       "parent_id":0,
       "purchase_note":"",
       "categories":[
          {
             "id":18,
             "name":"bakery",
             "slug":"bakery"
          }
       ],
       "tags":[
          
       ],
       "images":[
          {
             "id":65,
             "date_created":"2020-06-09T07:53:33",
             "date_created_gmt":"2020-06-09T07:53:33",
             "date_modified":"2020-06-09T07:53:33",
             "date_modified_gmt":"2020-06-09T07:53:33",
             "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Rice-Cakes-with-Chia-Seeds.jpg",
             "name":"Rice Cakes with Chia Seeds",
             "alt":""
          }
       ],
       "attributes":[
          
       ],
       "default_attributes":[
          
       ],
       "variations":[
          
       ],
       "grouped_products":[
          
       ],
       "menu_order":0,
       "meta_data":[
          {
             "id":729,
             "key":"_yith_pos_multistock_enabled",
             "value":"no"
          },
          {
             "id":730,
             "key":"_yith_pos_multistock",
             "value":[
                
             ]
          },
          {
             "id":750,
             "key":"_wc_facebook_sync_enabled",
             "value":"no"
          },
          {
             "id":819,
             "key":"_ywbc_barcode_protocol",
             "value":"EAN13"
          },
          {
             "id":820,
             "key":"_ywbc_barcode_value",
             "value":"64"
          },
          {
             "id":821,
             "key":"_ywbc_barcode_display_value",
             "value":"0000000000642"
          },
          {
             "id":822,
             "key":"ywbc_barcode_display_value_custom_field",
             "value":"0000000000642"
          },
          {
             "id":824,
             "key":"_ywbc_barcode_filename",
             "value":"\/customers\/f\/5\/6\/t-techsolutions.org\/httpd.www\/pos\/wp-content\/uploads\/yith-barcodes\/Image64_EAN13_64.png"
          }
       ],
       "yithPosImage":{
          "id":65,
          "date_created":"2020-06-09T07:53:33",
          "date_created_gmt":"2020-06-09T07:53:33",
          "date_modified":"2020-06-09T07:53:33",
          "date_modified_gmt":"2020-06-09T07:53:33",
          "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Rice-Cakes-with-Chia-Seeds-300x237.jpg",
          "name":"Rice Cakes with Chia Seeds",
          "alt":""
       },
       "_links":{
          "self":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/64"
             }
          ],
          "collection":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products"
             }
          ]
       }
    },
    {
       "id":62,
       "name":"Dark Chocolate with Nuts",
       "slug":"dark-chocolate-with-nuts",
       "permalink":"https:\/\/pos.t-techsolutions.org\/product\/dark-chocolate-with-nuts\/",
       "date_created":"2020-06-09T07:52:46",
       "date_created_gmt":"2020-06-09T07:52:46",
       "date_modified":"2020-06-09T07:52:47",
       "date_modified_gmt":"2020-06-09T07:52:47",
       "type":"simple",
       "status":"publish",
       "featured":false,
       "catalog_visibility":"visible",
       "description":"<p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n",
       "short_description":"",
       "sku":"6545698798",
       "price":"5.99",
       "regular_price":"6.99",
       "sale_price":"5.99",
       "date_on_sale_from":null,
       "date_on_sale_from_gmt":null,
       "date_on_sale_to":null,
       "date_on_sale_to_gmt":null,
       "price_html":"<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>6.99<\/bdi><\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>5.99<\/bdi><\/span><\/ins>",
       "on_sale":true,
       "purchasable":true,
       "total_sales":3,
       "virtual":false,
       "downloadable":false,
       "downloads":[
          
       ],
       "download_limit":-1,
       "download_expiry":-1,
       "external_url":"",
       "button_text":"",
       "tax_status":"taxable",
       "tax_class":"",
       "manage_stock":false,
       "stock_quantity":null,
       "stock_status":"instock",
       "backorders":"no",
       "backorders_allowed":false,
       "backordered":false,
       "sold_individually":false,
       "weight":"",
       "dimensions":{
          "length":"",
          "width":"",
          "height":""
       },
       "shipping_required":true,
       "shipping_taxable":true,
       "shipping_class":"",
       "shipping_class_id":0,
       "reviews_allowed":true,
       "average_rating":"0.00",
       "rating_count":0,
       "related_ids":[
          66,
          68,
          64,
          60
       ],
       "upsell_ids":[
          
       ],
       "cross_sell_ids":[
          
       ],
       "parent_id":0,
       "purchase_note":"",
       "categories":[
          {
             "id":18,
             "name":"bakery",
             "slug":"bakery"
          }
       ],
       "tags":[
          
       ],
       "images":[
          {
             "id":63,
             "date_created":"2020-06-09T07:52:41",
             "date_created_gmt":"2020-06-09T07:52:41",
             "date_modified":"2020-06-09T07:52:41",
             "date_modified_gmt":"2020-06-09T07:52:41",
             "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Dark-Chocolate-with-Nuts.jpg",
             "name":"Dark Chocolate with Nuts",
             "alt":""
          }
       ],
       "attributes":[
          
       ],
       "default_attributes":[
          
       ],
       "variations":[
          
       ],
       "grouped_products":[
          
       ],
       "menu_order":0,
       "meta_data":[
          {
             "id":702,
             "key":"_yith_pos_multistock_enabled",
             "value":"no"
          },
          {
             "id":703,
             "key":"_yith_pos_multistock",
             "value":[
                
             ]
          },
          {
             "id":723,
             "key":"_wc_facebook_sync_enabled",
             "value":"no"
          },
          {
             "id":825,
             "key":"_ywbc_barcode_protocol",
             "value":"EAN13"
          },
          {
             "id":826,
             "key":"_ywbc_barcode_value",
             "value":"62"
          },
          {
             "id":827,
             "key":"_ywbc_barcode_display_value",
             "value":"0000000000628"
          },
          {
             "id":828,
             "key":"ywbc_barcode_display_value_custom_field",
             "value":"0000000000628"
          },
          {
             "id":830,
             "key":"_ywbc_barcode_filename",
             "value":"\/customers\/f\/5\/6\/t-techsolutions.org\/httpd.www\/pos\/wp-content\/uploads\/yith-barcodes\/Image62_EAN13_62.png"
          }
       ],
       "yithPosImage":{
          "id":63,
          "date_created":"2020-06-09T07:52:41",
          "date_created_gmt":"2020-06-09T07:52:41",
          "date_modified":"2020-06-09T07:52:41",
          "date_modified_gmt":"2020-06-09T07:52:41",
          "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/Dark-Chocolate-with-Nuts-300x237.jpg",
          "name":"Dark Chocolate with Nuts",
          "alt":""
       },
       "_links":{
          "self":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/62"
             }
          ],
          "collection":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products"
             }
          ]
       }
    },
    {
       "id":60,
       "name":"Nut Chocolate Paste",
       "slug":"nut-chocolate-paste",
       "permalink":"https:\/\/pos.t-techsolutions.org\/product\/nut-chocolate-paste\/",
       "date_created":"2020-06-09T07:51:54",
       "date_created_gmt":"2020-06-09T07:51:54",
       "date_modified":"2020-06-09T07:51:54",
       "date_modified_gmt":"2020-06-09T07:51:54",
       "type":"simple",
       "status":"publish",
       "featured":false,
       "catalog_visibility":"visible",
       "description":"<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n",
       "short_description":"",
       "sku":"65461321",
       "price":"16.80",
       "regular_price":"18.80",
       "sale_price":"16.80",
       "date_on_sale_from":null,
       "date_on_sale_from_gmt":null,
       "date_on_sale_to":null,
       "date_on_sale_to_gmt":null,
       "price_html":"<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>18.80<\/bdi><\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>16.80<\/bdi><\/span><\/ins>",
       "on_sale":true,
       "purchasable":true,
       "total_sales":8,
       "virtual":false,
       "downloadable":false,
       "downloads":[
          
       ],
       "download_limit":-1,
       "download_expiry":-1,
       "external_url":"",
       "button_text":"",
       "tax_status":"taxable",
       "tax_class":"",
       "manage_stock":false,
       "stock_quantity":null,
       "stock_status":"instock",
       "backorders":"no",
       "backorders_allowed":false,
       "backordered":false,
       "sold_individually":false,
       "weight":"",
       "dimensions":{
          "length":"",
          "width":"",
          "height":""
       },
       "shipping_required":true,
       "shipping_taxable":true,
       "shipping_class":"",
       "shipping_class_id":0,
       "reviews_allowed":true,
       "average_rating":"0.00",
       "rating_count":0,
       "related_ids":[
          62,
          66,
          68,
          64
       ],
       "upsell_ids":[
          
       ],
       "cross_sell_ids":[
          
       ],
       "parent_id":0,
       "purchase_note":"",
       "categories":[
          {
             "id":18,
             "name":"bakery",
             "slug":"bakery"
          }
       ],
       "tags":[
          
       ],
       "images":[
          {
             "id":61,
             "date_created":"2020-06-09T07:51:29",
             "date_created_gmt":"2020-06-09T07:51:29",
             "date_modified":"2020-06-09T07:51:29",
             "date_modified_gmt":"2020-06-09T07:51:29",
             "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/bakery.png",
             "name":"bakery",
             "alt":""
          }
       ],
       "attributes":[
          
       ],
       "default_attributes":[
          
       ],
       "variations":[
          
       ],
       "grouped_products":[
          
       ],
       "menu_order":0,
       "meta_data":[
          {
             "id":675,
             "key":"_yith_pos_multistock_enabled",
             "value":"no"
          },
          {
             "id":676,
             "key":"_yith_pos_multistock",
             "value":[
                
             ]
          },
          {
             "id":696,
             "key":"_wc_facebook_sync_enabled",
             "value":"no"
          },
          {
             "id":831,
             "key":"_ywbc_barcode_protocol",
             "value":"EAN13"
          },
          {
             "id":832,
             "key":"_ywbc_barcode_value",
             "value":"60"
          },
          {
             "id":833,
             "key":"_ywbc_barcode_display_value",
             "value":"0000000000604"
          },
          {
             "id":834,
             "key":"ywbc_barcode_display_value_custom_field",
             "value":"0000000000604"
          },
          {
             "id":836,
             "key":"_ywbc_barcode_filename",
             "value":"\/customers\/f\/5\/6\/t-techsolutions.org\/httpd.www\/pos\/wp-content\/uploads\/yith-barcodes\/Image60_EAN13_60.png"
          }
       ],
       "yithPosImage":{
          "id":61,
          "date_created":"2020-06-09T07:51:29",
          "date_created_gmt":"2020-06-09T07:51:29",
          "date_modified":"2020-06-09T07:51:29",
          "date_modified_gmt":"2020-06-09T07:51:29",
          "src":"https:\/\/pos.t-techsolutions.org\/wp-content\/uploads\/2020\/06\/bakery-300x151.png",
          "name":"bakery",
          "alt":""
       },
       "_links":{
          "self":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products\/60"
             }
          ],
          "collection":[
             {
                "href":"https:\/\/pos.t-techsolutions.org\/wp-json\/wc\/v3\/products"
             }
          ]
       }
    }
 ]

